require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.2
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments